version: "3"
services:
  postgres:
    image: drstarland/testum-postgres:1.0
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  ticket-service:
    build:
      context: src/tickets
      dockerfile: Dockerfile
    image: drstarland/testum-tickets:1.0
    container_name: testum-tickets
    environment:
      PORT: "8070"
    ports:
      - "8070:8070"
    depends_on:
      - postgres

  flight-service:
    build:
      context: src/flights
      dockerfile: Dockerfile
    image: drstarland/testum-flights:1.0
    container_name: testum-flights
    environment:
      PORT: "8060"
    ports:
      - "8060:8060"
    depends_on:
      - postgres

  bonus-service:
    build:
      context: src/bonus
      dockerfile: Dockerfile
    image: drstarland/testum-bonus:1.0
    container_name: testum-bonus
    environment:
      PORT: "8050"
    ports:
      - "8050:8050"

  gateway-service:
    build:
      context: src/gateway
      dockerfile: Dockerfile
    image: drstarland/testum-gateway:1.0
    container_name: testum-gateway
    environment:
      PORT: "8080"
    ports:
      - "8080:8080"
    depends_on:
      - flight-service
      - ticket-service
      - bonus-service

volumes:
  db-data:

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16