name: GitHub Classroom Workflow

on:
  push:
    branches: [ master ]

env:
  KUBE_HOST: ${{ secrets.OKTETO_URL }}
  KUBE_TOKEN: ${{ secrets.OKTETO_TOKEN }}

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and publish images
        timeout-minutes: 10
        run: |
          docker compose build
          docker compose push
          docker compose up -d
          docker commit postgres drstarland/testum-postgres:1.0
          docker compose down
          docker push drstarland/testum-postgres:1.0
      
      - name: Deploy
        run: |
          kubectl config set-cluster flights-service-cluster --server="$KUBE_HOST" --insecure-skip-tls-verify=true
          kubectl config set-credentials cloud_okteto_com-user --token="$KUBE_TOKEN"
          kubectl config set-context default --cluster=flights-service-cluster --user=cloud_okteto_com-user --namespace="drstarland"
          kubectl config use-context default
          kubectl get pods
          cd k8s && helm upgrade --install --force --debug services services-chart/
          kubectl apply -f load-balancer.yaml
          sleep 45
          kubectl get pods

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v1/postman/collection.json
          environment: v1/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 5
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"